const P = 'https://picsum.photos/seed';

export const demoSongs = [
  {
    _id: 'song_001',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    artist_subtitle: 'The Weeknd',
    album: 'After Hours',
    release_date: '2019-11-29',
    duration_ms: 200040,
    cover_art_url: `${P}/melodix01/300/300`,
    artwork_url: `${P}/melodix01/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b',
    youtube_url: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    youtube: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    genre: 'Pop',
    artist_ids: ['artist_001'],
  },
  {
    _id: 'song_002',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    artist_subtitle: 'Ed Sheeran',
    album: '÷ (Divide)',
    release_date: '2017-01-06',
    duration_ms: 233712,
    cover_art_url: `${P}/melodix02/300/300`,
    artwork_url: `${P}/melodix02/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3',
    youtube_url: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    youtube: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    genre: 'Pop',
    artist_ids: ['artist_002'],
  },
  {
    _id: 'song_003',
    title: 'Levitating',
    artist: 'Dua Lipa',
    artist_subtitle: 'Dua Lipa ft. DaBaby',
    album: 'Future Nostalgia',
    release_date: '2020-10-01',
    duration_ms: 203806,
    cover_art_url: `${P}/melodix03/300/300`,
    artwork_url: `${P}/melodix03/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/39LLxExYz6ewLAcYrzQQyP',
    youtube_url: 'https://www.youtube.com/watch?v=TUVcZfQe-Kw',
    youtube: 'https://www.youtube.com/watch?v=TUVcZfQe-Kw',
    genre: 'Pop',
    artist_ids: ['artist_003'],
  },
  {
    _id: 'song_004',
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    artist_subtitle: 'The Kid LAROI, Justin Bieber',
    album: "F*CK LOVE 3: OVER YOU",
    release_date: '2021-07-09',
    duration_ms: 141805,
    cover_art_url: `${P}/melodix04/300/300`,
    artwork_url: `${P}/melodix04/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/5HCyWlXZPP0y6Gqq8TgA20',
    youtube_url: 'https://www.youtube.com/watch?v=kTJczUoc26U',
    youtube: 'https://www.youtube.com/watch?v=kTJczUoc26U',
    genre: 'Pop',
    artist_ids: ['artist_004'],
  },
  {
    _id: 'song_005',
    title: 'Dynamite',
    artist: 'BTS',
    artist_subtitle: 'BTS',
    album: 'Dynamite (DayTime Version)',
    release_date: '2020-08-21',
    duration_ms: 199054,
    cover_art_url: `${P}/melodix05/300/300`,
    artwork_url: `${P}/melodix05/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/0t1kP63rueHleOhQkYSXFY',
    youtube_url: 'https://www.youtube.com/watch?v=gdZLi9oWNZg',
    youtube: 'https://www.youtube.com/watch?v=gdZLi9oWNZg',
    genre: 'K-Pop',
    artist_ids: ['artist_005'],
  },
  {
    _id: 'song_006',
    title: 'Good 4 U',
    artist: 'Olivia Rodrigo',
    artist_subtitle: 'Olivia Rodrigo',
    album: 'SOUR',
    release_date: '2021-05-14',
    duration_ms: 178455,
    cover_art_url: `${P}/melodix06/300/300`,
    artwork_url: `${P}/melodix06/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/4ZtFanR9U6ndgddUvNcjcG',
    youtube_url: 'https://www.youtube.com/watch?v=gNi_6U5Pm_o',
    youtube: 'https://www.youtube.com/watch?v=gNi_6U5Pm_o',
    genre: 'Pop',
    artist_ids: ['artist_006'],
  },
  {
    _id: 'song_007',
    title: 'Peaches',
    artist: 'Justin Bieber',
    artist_subtitle: 'Justin Bieber ft. Daniel Caesar & Giveon',
    album: 'Justice',
    release_date: '2021-03-19',
    duration_ms: 198082,
    cover_art_url: `${P}/melodix07/300/300`,
    artwork_url: `${P}/melodix07/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/4iJyoBOLtHqaWYs3pugAVk',
    youtube_url: 'https://www.youtube.com/watch?v=tQ0yjYUFKAE',
    youtube: 'https://www.youtube.com/watch?v=tQ0yjYUFKAE',
    genre: 'Pop',
    artist_ids: ['artist_007'],
  },
  {
    _id: 'song_008',
    title: 'Butter',
    artist: 'BTS',
    artist_subtitle: 'BTS',
    album: 'Butter',
    release_date: '2021-05-21',
    duration_ms: 164442,
    cover_art_url: `${P}/melodix08/300/300`,
    artwork_url: `${P}/melodix08/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/1mWdTewIgB3gtBM3TOSFhB',
    youtube_url: 'https://www.youtube.com/watch?v=WMweEpGlu_U',
    youtube: 'https://www.youtube.com/watch?v=WMweEpGlu_U',
    genre: 'K-Pop',
    artist_ids: ['artist_005'],
  },
  {
    _id: 'song_009',
    title: 'Leave the Door Open',
    artist: 'Silk Sonic',
    artist_subtitle: 'Bruno Mars, Anderson .Paak, Silk Sonic',
    album: 'An Evening with Silk Sonic',
    release_date: '2021-03-05',
    duration_ms: 243032,
    cover_art_url: `${P}/melodix09/300/300`,
    artwork_url: `${P}/melodix09/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/0GKEv0MbCf8Z3RJBI9eFZl',
    youtube_url: 'https://www.youtube.com/watch?v=adLGHcj_GMY',
    youtube: 'https://www.youtube.com/watch?v=adLGHcj_GMY',
    genre: 'R&B',
    artist_ids: ['artist_008'],
  },
  {
    _id: 'song_010',
    title: 'Montero',
    artist: 'Lil Nas X',
    artist_subtitle: 'Lil Nas X',
    album: 'MONTERO',
    release_date: '2021-03-26',
    duration_ms: 137533,
    cover_art_url: `${P}/melodix10/300/300`,
    artwork_url: `${P}/melodix10/600/600`,
    preview_url: null,
    spotify_url: 'https://open.spotify.com/track/7ClZ3V9l1wK3K0jjl8h4YI',
    youtube_url: 'https://www.youtube.com/watch?v=6swmTBVI83k',
    youtube: 'https://www.youtube.com/watch?v=6swmTBVI83k',
    genre: 'Hip-Hop',
    artist_ids: ['artist_009'],
  },
];

export const demoArtists = [
  { _id: 'artist_001', name: 'The Weeknd', slug: 'the-weeknd', image_url: `${P}/melodixar01/300/300` },
  { _id: 'artist_002', name: 'Ed Sheeran', slug: 'ed-sheeran', image_url: `${P}/melodixar02/300/300` },
  { _id: 'artist_003', name: 'Dua Lipa', slug: 'dua-lipa', image_url: `${P}/melodixar03/300/300` },
  { _id: 'artist_005', name: 'BTS', slug: 'bts', image_url: `${P}/melodixar05/300/300` },
];

export const demoPlaylists = [
  {
    _id: 'playlist_001',
    playlist_name: 'My Favorites',
    ownerId: '__DEVICE_ID__',
    deviceIds: ['__DEVICE_ID__'],
    tracks: [demoSongs[0], demoSongs[1], demoSongs[2]],
  },
  {
    _id: 'playlist_002',
    playlist_name: 'Chill Vibes',
    ownerId: '__DEVICE_ID__',
    deviceIds: ['__DEVICE_ID__'],
    tracks: [demoSongs[3], demoSongs[4], demoSongs[5]],
  },
  {
    _id: 'playlist_003',
    playlist_name: 'Party Mix',
    ownerId: '__DEVICE_ID__',
    deviceIds: ['__DEVICE_ID__'],
    tracks: [demoSongs[6], demoSongs[7], demoSongs[8], demoSongs[9]],
  },
];

export const demoConcertsMap: Record<string, any[]> = {
  artist_001: [
    {
      id: 'concert_001',
      title: 'The Weeknd – After Hours Til Dawn Tour',
      datetime: '2025-09-15T20:00:00Z',
      venue: { name: 'Gelora Bung Karno', city: 'Jakarta', region: 'DKI Jakarta', country: 'Indonesia', latitude: '-6.2183', longitude: '106.8025' },
      lineup: ['The Weeknd'],
      description: 'The Weeknd brings his iconic After Hours Til Dawn Tour to Jakarta.',
      url: 'https://www.ticketmaster.com',
      offers: [],
    },
    {
      id: 'concert_002',
      title: 'The Weeknd – After Hours Til Dawn Tour',
      datetime: '2025-10-02T19:00:00Z',
      venue: { name: 'Singapore Indoor Stadium', city: 'Singapore', region: '', country: 'Singapore', latitude: '1.3001', longitude: '103.8750' },
      lineup: ['The Weeknd'],
      description: '',
      url: 'https://www.ticketmaster.com',
      offers: [],
    },
  ],
  artist_002: [
    {
      id: 'concert_003',
      title: 'Ed Sheeran – Mathematics Tour',
      datetime: '2025-11-20T19:30:00Z',
      venue: { name: 'Stadion Utama GBK', city: 'Jakarta', region: 'DKI Jakarta', country: 'Indonesia', latitude: '-6.2180', longitude: '106.8020' },
      lineup: ['Ed Sheeran'],
      description: 'Ed Sheeran brings the Mathematics Tour to Southeast Asia.',
      url: 'https://www.ticketmaster.com',
      offers: [],
    },
  ],
  artist_003: [
    {
      id: 'concert_004',
      title: 'Dua Lipa – Radical Optimism Tour',
      datetime: '2025-08-10T20:00:00Z',
      venue: { name: 'Jakarta International Expo', city: 'Jakarta', region: 'DKI Jakarta', country: 'Indonesia', latitude: '-6.1456', longitude: '106.8878' },
      lineup: ['Dua Lipa'],
      description: '',
      url: 'https://www.ticketmaster.com',
      offers: [],
    },
  ],
  artist_005: [
    {
      id: 'concert_005',
      title: 'BTS World Tour',
      datetime: '2025-12-05T18:00:00Z',
      venue: { name: 'KSPO Dome', city: 'Seoul', region: '', country: 'South Korea', latitude: '37.5172', longitude: '127.1231' },
      lineup: ['BTS'],
      description: '',
      url: 'https://www.ticketmaster.com',
      offers: [],
    },
  ],
};

export const defaultConcerts = [
  {
    id: 'concert_default',
    title: 'Live in Concert 2025',
    datetime: '2025-10-10T20:00:00Z',
    venue: { name: 'Jakarta Convention Center', city: 'Jakarta', region: 'DKI Jakarta', country: 'Indonesia', latitude: '-6.2088', longitude: '106.8456' },
    lineup: ['Artist'],
    description: 'An unforgettable live performance.',
    url: '#',
    offers: [],
  },
];
